# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='size',
            field=models.CharField(choices=[('0', '1-50'), ('1', '51-100'), ('2', '101-1000')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
