# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0003_employer_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='size',
            field=models.CharField(choices=[('1-50', '1-50'), ('51-100', '51-100'), ('101-1000', '101-1000')], max_length=255, null=True),
        ),
    ]
