# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='skills',
            field=models.ManyToManyField(related_name='skills', to='users.Skill'),
        ),
    ]
