# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 05:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_project'),
        ('students', '0003_auto_20170409_2244'),
    ]

    operations = [
    ]
