# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_merge_20170410_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='skills',
            field=models.ManyToManyField(to='users.Skill'),
        ),
    ]
