# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20170412_0126'),
        ('students', '0008_auto_20170411_0446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='position',
        ),
        migrations.AddField(
            model_name='student',
            name='position',
            field=models.ManyToManyField(null=True, to='users.Position'),
        ),
    ]
