# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20170412_0126'),
        ('students', '0009_auto_20170422_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='position',
        ),
        migrations.AddField(
            model_name='student',
            name='position',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Position'),
        ),
    ]
