# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20170422_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='position',
            field=models.CharField(choices=[('Intern', 'Intern'), ('Full Time', 'Full Time')], max_length=50, null=True),
        ),
    ]
