# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_messages', '0002_auto_20160607_0852'),
        ('job', '0006_job_skills'),
        ('account', '0002_email_max_length'),
        ('students', '0001_initial'),
        ('admin', '0002_logentry_remove_auto_add'),
        ('socialaccount', '0003_extra_data_default_dict'),
        ('posts', '0001_initial'),
        ('employers', '0004_auto_20170303_2304'),
        ('users', '0005_merge_20170304_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Employer',
        ),
    ]
