# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170322_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('Intern', 'Intern'), ('Full Time', 'Full Time')], max_length=255)),
            ],
        ),
    ]
