# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='position',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Position'),
        ),
    ]
