# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 17:58
from __future__ import unicode_literals

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('employers', '0002_auto_20170301_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='location',
            field=address.models.AddressField(null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Address'),
        ),
    ]
