# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 16:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=200, null=True)),
                ('employment_type', models.CharField(choices=[('INTERN', 'Intern'), ('FULL TIME', 'FULL TIME')], max_length=200, null=True)),
                ('industry', models.CharField(choices=[('Tech', 'Technology Company'), ('Busi', 'Business'), ('Medi', 'Medicine')], max_length=200, null=True)),
                ('location', models.CharField(choices=[('CA', 'California'), ('WA', 'Washington')], max_length=200, null=True)),
                ('experience', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
