# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170303_2141'),
        ('job', '0005_auto_20170303_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(null=True, to='users.Skill'),
        ),
    ]
