# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('students', '0001_initial'),
        ('admin', '0002_logentry_remove_auto_add'),
        ('account', '0002_email_max_length'),
        ('socialaccount', '0003_extra_data_default_dict'),
        ('django_messages', '0002_auto_20160607_0852'),
        ('job', '0006_job_skills'),
        ('employers', '0004_auto_20170303_2304'),
    ]
