# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20170326_1918'),
        ('users', '0005_merge_20170326_1940'),
    ]

    operations = [
    ]
