# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20170409_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='name',
            new_name='skill',
        ),
    ]
