# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_user_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='short_description',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
