# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 05:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20170409_1556'),
        ('users', '0018_user_short_description'),
    ]

    operations = [
    ]
