# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_auto_20170409_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(null=True, related_name='reqskills', to='users.Skill'),
        ),
    ]
