# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='education_weightage',
            field=models.IntegerField(default=33),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_weight',
            field=models.IntegerField(default=33),
        ),
        migrations.AddField(
            model_name='job',
            name='skills_weight',
            field=models.IntegerField(default=33),
        ),
    ]
