# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0019_jobapplication_attachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='experience_weight',
            new_name='experience_weightage',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='skills_weight',
            new_name='skills_weightage',
        ),
        migrations.AlterField(
            model_name='job',
            name='education_weightage',
            field=models.IntegerField(default=34),
        ),
    ]
