# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0021_auto_20170422_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='attachment',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
